######################################################################
# Automatically generated by qmake (1.07a) Sat Nov 11 19:30:21 2006
######################################################################

TEMPLATE = app
CONFIG  += release
INCLUDEPATH +=  . /opt/local/include \
                  /Users/erxingfangshui/Dropbox/eigen3 \
		  /Users/erxingfangshui/Dropbox/eigen3/Eigen \
		   /Users/erxingfangshui/Dropbox/matvec/include \
		   /Users/erxingfangshui/Dropbox/matvec

LIBS +=           /Users/erxingfangshui/Dropbox/matvec/lib/libmatvec.a


# Input
SOURCES += main_CalculateA.cpp

CXXFLAGS +=

QMAKE_CXX = mpic++
QMAKE_LINK = mpic++
